export const INTERACTION_UNION_TYPE = {
  SHARE: 'SHARE',
  USER_REPORT: 'USER_REPORT',
  RECOMMEND: 'RECOMMEND',
  UN_RECOMMEND: 'UN_RECOMMEND',
} as const

export type INTERACTION_TYPE = (typeof INTERACTION_UNION_TYPE)[keyof typeof INTERACTION_UNION_TYPE]
